### ISSUE TITLE
[Bug]  [WinError 3] 系统找不到指定的路径。: 'tmp\\Honkai-Star-Rail-beta-map/temp'

### ISSUE THREAD

**Issue by FlashIvano** [Starry-Wind/Honkai-Star-Rail#140]
### 问题描述

window的bat运行报错：

```
正在自动更新地图档
update_file.update_file_main:231 - 2.9 - [资源文件更新]即将资源文件更新，本操作会覆盖本地地图文件..
update_file.update_file:118 - 2.9 - [资源文件更新]正在检查远程版本是否有更新...
update_file.update_file:134 - 2.9 - [资源文件更新]获取远程版本成功: 20230512201117
update_file.update_file:139 - 2.9 - [资源文件更新]本地版本与远程版本不符，开始更新资源文件->https://github.com/Starry-Wind/Honkai-Star-Rail/archive/refs/heads/map.zip
map.zip: 100%|███████████████████████████████████████████████████████████████████| 1.33M/1.33M [00:00<00:00, 2.46MiB/s]
update_file.update_file:150 - 2.9 - [资源文件更新]下载更新包成功, 正在覆盖本地文件: 0 -> 20230512201117
解压中: 100%|██████████████████████████████████████████████████████████████████████| 141/141 [00:00<00:00, 5925.76it/s]
update_file.update_file:158 - 2.9 - [资源文件更新]正在校验资源文件
update_file.update_file:166 - 2.9 - [资源文件更新]校验完成, 更新本地地图文件版本号 0 -> 20230512201117
update_file.update_file:171 - 2.9 - [资源文件更新]删除临时文件tmp
update_file.update_file:201 - 2.9 - [资源文件更新]更新完成.
update_file.update_file_main:231 - 2.9 - [资源文件更新]即将资源文件更新，本操作会覆盖本地图片文件..
update_file.update_file:118 - 2.9 - [资源文件更新]正在检查远程版本是否有更新...
update_file.update_file:134 - 2.9 - [资源文件更新]获取远程版本成功: 20230512201117
update_file.update_file:139 - 2.9 - [资源文件更新]本地版本与远程版本不符，开始更新资源文件->https://github.com/Starry-Wind/Honkai-Star-Rail/archive/refs/heads/map.zip
map.zip: 100%|███████████████████████████████████████████████████████████████████| 1.33M/1.33M [00:00<00:00, 2.47MiB/s]
update_file.update_file:150 - 2.9 - [资源文件更新]下载更新包成功, 正在覆盖本地文件: 0 -> 20230512201117
解压中: 100%|████████████████████████████████████████████████████████████████████████████████| 141/141 [00:00<?, ?it/s]
Honkai_Star_Rail.<module>:100 - 2.9 - Traceback (most recent call last):
  File "D:\GREENS~1\GameSoft\HONKAI~1\Honkai_Star_Rail.py", line 92, in <module>
    main()
  File "D:\GREENS~1\GameSoft\HONKAI~1\Honkai_Star_Rail.py", line 68, in main
    update_file_main(**up)
  File "D:\GREENS~1\GameSoft\HONKAI~1\tool\update_file.py", line 232, in update_file_main
    check_file_status = asyncio.run(update_file(url_proxy,False,skip_verify,type,version,url_zip,unzip_path,keep_folder,keep_file,zip_path))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\GREENS~1\GameSoft\HONKAI~1\tool\update_file.py", line 156, in update_file
    await move_file(os.path.join(tmp_dir, zip_path), unzip_path, [], keep_file)
  File "D:\GREENS~1\GameSoft\HONKAI~1\tool\update_file.py", line 68, in move_file
    for item in os.listdir(src_folder):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'tmp\\Honkai-Star-Rail-beta-map/temp'
```

### 预期行为

不报错

### 实际行为

报错

### 自动锄大地脚本版本

1.0.4

### 星穹铁道区服

国服

### 日志

[日志文件.log](https://github.com/Starry-Wind/Honkai-Star-Rail/files/11468661/default.log)

**Comment by Klamist** [comment]
我也是这个问题。
然后，我手动解压tmp里的.zip，然后文件夹改名Honkai-Star-Rail-beta-map。然后重新运行bat执行文件，继续报错，但试了5次，就OK了。
我不清楚是哪一步解决的。你可以多试试。

**Comment by Night-stars-1** [comment]
请更新最新版，这个问题在凌晨4点就修复了
