### ISSUE TITLE
[Bug] FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: '.'

### ISSUE THREAD

**Issue by Agnes4m** [Starry-Wind/Honkai-Star-Rail#200]
### 问题描述

# 启动程序初始化过程中，遇到报错。
## 环境
- windows10
- python 3.11.3
- 已安装requirements.txt的依赖（已尝试过poetry安装和全局安装）

## 操作：
- 下载[Releases 18](https://github.com/Starry-Wind/Honkai-Star-Rail/releases)最新版本
- 解压
- 执行`Honkai_Star_Rail.py`
- 按照要求选择了代理，和是否开启自动战斗

### 预期行为

在输入代理配置后，正确生成配置，正确下载资源解压，并启动脚本

### 实际行为

初始化失败，并且失败后文件不完整导致无法继续操作/纠正操作
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/70925546/e9774b8e-aebb-493f-8fda-9e91cd9eaa61)

### 截图或录屏

```
PS E:\text\github\auto\sr\Honkai-Star-Rail-1.1.6> py Honkai_Star_Rail.py
update_file.update_file_main:260 - 3.1 - [资源文件更新]即将资源文件更新，本操作会覆盖本地脚本文件..
update_file.update_file:128 - 3.1 - [资源文件更新]正在检查远程版本是否有更新...
update_file.update_file:146 - 3.1 - [资源文件更新]获取远程版本成功: 20230515212946
update_file.update_file:151 - 3.1 - [资源文件更新]本地版本与远程版本不符，开始更新资源文件->https://ghproxy.net/https://github.com/Starry-Wind/Honkai-Star-Rail/archive/refs/heads/beta-2.7_test.zip
beta-2.7_test.zip: 100%|██████████████████████████████████████████████████████████| 38.8k/38.8k [00:00<00:00, 592kiB/s]
update_file.update_file:155 - 3.1 - [资源文件更新]下载更新包成功, 正在覆盖本地文件: 0 -> 20230515212946
解压中: 100%|█████████████████████████████████████████████████████████████████████████| 40/40 [00:00<00:00, 366.92it/s]
Honkai_Star_Rail.<module>:122 - 3.1 - Traceback (most recent call last):
  File "E:\text\github\auto\sr\Honkai-Star-Rail-1.1.6\Honkai_Star_Rail.py", line 112, in <module>
    main()
  File "E:\text\github\auto\sr\Honkai-Star-Rail-1.1.6\Honkai_Star_Rail.py", line 20, in main
    up_data()
  File "E:\text\github\auto\sr\Honkai-Star-Rail-1.1.6\Honkai_Star_Rail.py", line 105, in up_data
    update_file_main(**up)
  File "E:\text\github\auto\sr\Honkai-Star-Rail-1.1.6\tools\update_file.py", line 261, in update_file_main
  File "D:\python3.11\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\python3.11\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python3.11\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\text\github\auto\sr\Honkai-Star-Rail-1.1.6\tools\update_file.py", line 171, in update_file
  File "E:\text\github\auto\sr\Honkai-Star-Rail-1.1.6\tools\update_file.py", line 68, in move_file
  File "<frozen os>", line 225, in makedirs
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: '.'
```

### 自动锄大地脚本版本

1.1.6

### 星穹铁道区服

国服

### 日志

[日志文件.log](https://github.com/Starry-Wind/Honkai-Star-Rail/files/11478378/default.log)

**Comment by Night-stars-1** [comment]
已修复v1.1.6
